LONGINT_IMPL = MPZ
INTERNAL_LIBM = 1

# We build .elf files to run in the simulator. Generally, this will be a file
# type supported by the chip family's bootloader.
CIRCUITPY_BUILD_EXTENSIONS = elf

CIRCUITPY_STORAGE = 1
CIRCUITPY_INTERNAL_FLASH_FILESYSTEM = 1
INTERNAL_FLASH_FILESYSTEM = 1
CIRCUITPY_FILESYSTEM_FLUSH_INTERVAL_MS = 1000

CIRCUITPY_SUPERVISOR_RUNTIME = 1

# Usually lots of flash space available
CIRCUITPY_MESSAGE_COMPRESSION_LEVEL = 1

CIRCUITPY_RANDOM = 1

CIRCUITPY_USB_DEVICE = 0

# Disable modules included in full builds
CIRCUITPY_FULL_BUILD = 0

# Disable modules included in slim builds directly. Enable these as they are
# implemented.
CIRCUITPY_ANALOGBUFIO = 0
CIRCUITPY_ANALOGIO = 0
CIRCUITPY_BUSIO_I2C = 0
CIRCUITPY_BUSIO_SPI = 0
CIRCUITPY_DIGITALIO = 0
CIRCUITPY_BITBANGIO = 0
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_NVM = 0
CIRCUITPY_ONEWIREIO = 0
CIRCUITPY_PWMIO = 0
CIRCUITPY_ROTARYIO = 0
CIRCUITPY_ROTARYIO_SOFTENCODER = 0
CIRCUITPY_RTC = 0
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_STATUS_BAR = 0

